### ISSUE TITLE
Table of Contents flicks on hover in Japanese

### ISSUE THREAD

**Issue by dopin** [ember-learn/guides-app#15]
This happens in Japanese at the moment on a specific condition.

![flickering](https://user-images.githubusercontent.com/11515/34826789-5d4528b6-f71b-11e7-95ce-611ea317e953.gif)

- Firefox 57.0.4 on Mac High Sierra

**Comment by mansona** [comment]
@dopin I think because we are not officially supporting translations (at this moment) it's not something that we are going to fix from our end 😖 

what I **can** say is that you can change the CSS in your fork to stop that offset happening on hover, let me know how that goes and we can close this issue 👍

**Comment by mansona** [comment]
Hey @dopin 👋 

I tried to move this issue to your fork but it seems like you don't have issues turned on so I can't file an issue. You can turn it on in the settings ([here](https://cl.ly/383435410d3Y/Screen%20Shot%202018-01-15%20at%2007.53.46.png) is what it looks like in my fork) 

I want to start filling out some of the issues here so I'm afraid I'm going to have to close this one. Ping me on #-team-learning if you want to discuss how to fix this on your branch 👍

**Comment by dopin** [comment]
@mansona Hi! Thanks! That's fine 👍 I'll tackle this issue after I finish translation 😉
