### ISSUE TITLE
Line highlighting & code highlighting bugs

### ISSUE THREAD

**Issue by mansona** [ember-learn/guides-app#21]
- [x] re-implement the diff system for code highlights
- [ ] ensure things like {{outlet}} are still getting highlighted. 
- [ ] extend prism's diff language to diff + js & diff + hbs

**Comment by jessieay** [comment]
Just found a specific bug. Not sure if it is fixed by existing work that hasn't been deployed yet, but this is what I see:

Guides URL: https://guides.emberjs.com/v3.1.0/tutorial/autocomplete-component/

Diff that is highlighted improperly:
![screen shot 2018-05-16 at 11 34 17 am](https://user-images.githubusercontent.com/601515/40136693-53211996-58fd-11e8-8a86-3a23d9be0bb4.png)

Note that lines 29 and 30 are marked red when they shouldn't be. Here is the markdown on L306 at `guides/v3.1.0/tutorial/autocomplete-component.md`:

```
javascript {data-filename="tests/integration/components/list-filter-test.js"      data-diff="+9,+10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,-25,-26,-27,-28"}
```

When following along with the tutorial, I deleted this line and then realized that it introduced a syntax error.

**Comment by mansona** [comment]
@jessieay thanks for the report! It looks like that specific issue is fixed in the new system already. You can see it on our test URL here: https://emberguides.stonecircle.io/release/tutorial/autocomplete-component/#toc_an-integration-test

we should hopefully be swapping this to go live very soon so it should be fixed on the live URL 👍

**Comment by jessieay** [comment]
@mansona I noticed when running the guides app locally (after making this comment) that the diff highlighting looks different now. Looks nice. 

One piece of feedback on the new highlighting is that comments are very hard to read when highlighted in either color.

**Comment by mansona** [comment]
it looks like @jenweber has solved that one 🎉 https://github.com/ember-learn/guides-app/pull/75

**Comment by mansona** [comment]
@sivakumar-kailasam there was one checkmark on this that is still relevant `ensure things like {{outlet}} are still getting highlighted.` which is related to us using handlebars instead of htmlbars as the language in Prism (there is not yet a htmlbars language 😂) 

do you mind if I re-open this to at least keep track?

**Comment by sivakumar-kailasam** [comment]
I believe I've fixed it. Can you reopen in case it's still an issue

**Comment by mansona** [comment]
looks like it's working 🎉 ignore me
