### ISSUE TITLE
Remove patch versions & 'v' prefix in version dropdown

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/guides-app#58]
The patch version in version selector dropdown has been removed in the api docs so as to avoid confusion when patch releases are made on ember/ember-data. We also did away with the `v` prefix. 

We instead used only `majorVer.minorVer` in dropdown and urls.(eg 3.1, 2.18) We also added route support to allow for old urls with patch versions in them to still resolve to the latest patch version of what was entered. e.g., https://emberjs.com/api/ember/3.1.10/modules/@ember%2Fapplication will still resolve to https://emberjs.com/api/ember/3.1/modules/@ember%2Fapplication.

This will give a sense of familiarity between using guides & api docs.

**Comment by progand** [comment]
Do you still need any help here?

**Comment by mansona** [comment]
@progand yes we would love if you could take a look at this 🎉 

If you need any help getting started then reach out to us on the #-team-learning Slack channel, but as this issue is most likely just an update to the Ember app it is likely you can just clone then `npm i` and `npm start` to get started 💪

**Comment by progand** [comment]
Guys, this is my first PR here so please, check carefully. I hope I correctly understood the issue

**Comment by progand** [comment]
@mansona  sorry for misundertanding. I think my latest PR is what you need
