### ISSUE TITLE
“View quick start guide” link from emberjs.com is broken

### ISSUE THREAD

**Issue by chris-morgan** [ember-learn/guides-app#88]
Probably related to #57.

On https://www.emberjs.com/, the “view quick start guide” link goes to https://guides.emberjs.com/current/getting-started/quick-start/ which is a 404; it should be https://guides.emberjs.com/release/getting-started/quick-start/ instead.

If the link was always broken, it should just be fixed; but presuming that it worked once upon a time, a redirect should be added so that /current/* goes to /release/*.

When the primary call to action from the home page is a broken link, a very bad impression is left!

**Comment by mansona** [comment]
This has been fixed by #91 

Although it's related to #57 it wouldn't be *solved* that, we need to make sure that all **existing** internal links to the guides still work even if we don't have "control" over the source of that link.

That being said @chris-morgan, would you like to help us on #57 but updating the link on the website?

**Comment by chris-morgan** [comment]
Nah, ’fraid I don’t care enough about it at present. Thanks for fixing the more urgent issue, though. ☺
